name: CI - Build ZIPs

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build zips
        run: |
          mkdir -p dist
          for dir in plugins/*/ ; do
            name=$(basename "$dir")
            zip -rq "dist/${name}.zip" "$dir"
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
