name: PHPUnit

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        working-directory: plugins/g3d-models-manager
        run: composer install --no-interaction --no-progress

      - name: Run PHPUnit
        working-directory: plugins/g3d-models-manager
        run: vendor/bin/phpunit
